<?php
return array (
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '908',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'sort' => '907',
    'from' => 'videojs',
    'show' => 'videojs-H5播放器',
    'des' => 'videojs.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'iva-H5播放器',
    'des' => 'videojj.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '906',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'ps' => '0',
    'parse' => '',
    'sort' => '905',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'sort' => '904',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '1',
    'sort' => '903',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'flv' => 
  array (
    'status' => '1',
    'from' => 'flv',
    'show' => 'Flv文件',
    'des' => 'flv',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '902',
    'tip' => '无需安装任何插件	',
    'id' => 'flv',
  ),
  'bfzym3u8' => 
  array (
    'status' => '1',
    'from' => 'bfzym3u8',
    'show' => '暴风资源',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://bfzyplayer.com/player/?url=',
    'sort' => '99',
    'tip' => '',
  ),
  'ffm3u8' => 
  array (
    'status' => '1',
    'from' => 'ffm3u8',
    'show' => '非凡资源M3U8',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://ffzyplayer.com/?url=',
    'sort' => '99',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'ffm3u8',
  ),
  'leshi' => 
  array (
    'status' => '1',
    'from' => 'leshi',
    'show' => '乐视资源',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://leshivideoplayurl.com/?url=  ',
    'sort' => '99',
    'tip' => '',
  ),
  'kuaikan' => 
  array (
    'status' => '1',
    'from' => 'kuaikan',
    'show' => '快看资源',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://kkzyplayer.com/player/?url=',
    'sort' => '99',
    'tip' => '',
  ),
  'feifan' => 
  array (
    'status' => '1',
    'from' => 'feifan',
    'show' => '非凡资源',
    'des' => 'http://ffzy.tv/',
    'target' => '_self',
    'ps' => '1',
    'parse' => '',
    'sort' => '99',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'feifan',
  ),
);